{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "avg by (instance) (node_load1)", "legendFormat": "1m" },
    { "expr": "avg by (instance) (node_load5)", "legendFormat": "5m" },
    {
     "expr": "avg by (instance) (node_load15)",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) by (instance)",
     "legendFormat": "Free"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) by (instance)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}